/** Executable traceability map from Web operations to their terminal equivalent. */
export const TUI_CAPABILITIES = [
    { id: 'prompt', entry: 'composer', service: 'Agent.followup', effect: 'execute', testId: 'controller:prompt', status: 'mapped' },
    { id: 'cancel', entry: 'Ctrl+C', service: 'Agent.cancel', effect: 'execute', testId: 'controller:cancel', status: 'mapped' },
    { id: 'commands', entry: '/ menu', service: 'CommandRuntime.list/execute', effect: 'execute', testId: 'catalog:dynamic', status: 'mapped' },
    { id: 'model', entry: '/models /model', service: 'LlmRuntime + ModelSelectionRef', effect: 'write', testId: 'terminal:model', status: 'mapped' },
    { id: 'credentials', entry: '/credentials', service: 'CredentialProvider', effect: 'write', testId: 'terminal:credentials', status: 'mapped' },
    { id: 'permission', entry: '/permission + approval panel', service: 'PermissionPresetService + approval/request', effect: 'write', testId: 'decision:approval', status: 'mapped' },
    { id: 'plan', entry: '/plan', service: 'CommandRuntime', effect: 'write', testId: 'catalog:harness', status: 'mapped' },
    { id: 'goal', entry: '/goal', service: 'CommandRuntime', effect: 'write', testId: 'catalog:harness', status: 'mapped' },
    { id: 'preset', entry: '/presets /preset', service: 'AgentPresets', effect: 'write', testId: 'terminal:preset', status: 'mapped' },
    { id: 'sessions', entry: '/new /sessions /resume', service: 'AgentFactory + SessionQueryEngine', effect: 'write', testId: 'terminal:sessions', status: 'mapped' },
    { id: 'session-search', entry: '/sessions <query>', service: 'SessionQueryEngine.searchSessions/filterEvents', effect: 'read', testId: 'terminal:session-search', status: 'mapped' },
    { id: 'session-stats', entry: '/stats', service: 'SessionProjectionRegistry.sessionStats', effect: 'read', testId: 'terminal:stats', status: 'mapped' },
    { id: 'rename', entry: '/rename', service: 'SessionTitleService.rename', effect: 'write', testId: 'terminal:rename', status: 'mapped' },
    { id: 'export', entry: '/export', service: 'SessionQueryEngine + AttachmentStore', effect: 'read', testId: 'export:archive', status: 'mapped' },
    { id: 'attachments', entry: '/attach', service: 'AttachmentStore.save', effect: 'write', testId: 'terminal:attachment', status: 'mapped' },
    { id: 'skills', entry: '/skills + /<skill>', service: 'SkillRegistry', effect: 'execute', testId: 'catalog:skill', status: 'mapped' },
    { id: 'subagents', entry: '/subagents', service: 'SubagentRuntime.list/listChildren', effect: 'read', testId: 'terminal:subagents', status: 'mapped' },
    { id: 'tools', entry: 'transcript tool cards', service: 'Agent tool runtime', effect: 'execute', testId: 'presenter:tool', status: 'mapped' },
    { id: 'approvals', entry: 'approval panel', service: 'approval/request', effect: 'write', testId: 'decision:approval', status: 'mapped' },
    { id: 'questions', entry: 'question panel', service: 'UserQuestionsService', effect: 'write', testId: 'decision:questions', status: 'mapped' },
    { id: 'jobs', entry: '/jobs /job-read /job-kill', service: 'JobsService', effect: 'write', testId: 'terminal:jobs', status: 'mapped' },
    { id: 'workflows', entry: '/ menu + transcript cards', service: 'WorkflowEngine', effect: 'execute', testId: 'presenter:workflow', status: 'mapped' },
    { id: 'deliverables', entry: 'transcript deliverables', service: 'SessionEvent surface', effect: 'read', testId: 'presenter:deliverables', status: 'mapped' },
    { id: 'trajectory', entry: '/trajectory', service: 'Session.events', effect: 'read', testId: 'terminal:trajectory', status: 'mapped' },
    { id: 'workspace', entry: '/workspace', service: 'WorkspaceRegistry', effect: 'write', testId: 'terminal:workspace', status: 'mapped' },
    { id: 'settings', entry: '/settings', service: 'SettingsProvider.describe/mutate', effect: 'write', testId: 'terminal:settings', status: 'mapped' },
    { id: 'plugins', entry: '/plugins', service: 'PluginInventoryGateway', effect: 'read', testId: 'terminal:plugins', status: 'mapped' },
    { id: 'session-feedback', entry: '/feedback', service: 'CommandRuntime', effect: 'write', testId: 'catalog:harness', status: 'mapped' },
    { id: 'message-feedback', entry: '/message-feedback', service: 'MessageFeedbackService', effect: 'write', testId: 'terminal:message-feedback', status: 'mapped' },
];
//# sourceMappingURL=capability-matrix.js.map